### ISSUE TITLE
[Log in page] Log in with Facebook doesn't work

### ISSUE THREAD

**Issue by VeronikaChorna** [ita-social-projects/horondi_client_be#1066]
Environment Windows 10, Chrome Version 96.0.4664.110
Reproducible: Always

**Preconditions:**

Go to https://horondi-front-staging.azurewebsites.net/

**Steps to reproduce:**

1. Go to 'Log in' page.
2. Click on 'Facebook' button.

**Actual result:** 'JSSDK Unknown Host domain' page appears.
![eyf](https://user-images.githubusercontent.com/96176970/150545058-9ca47fe3-2da9-4761-bd09-3cc6d27dd851.PNG)
![eaf](https://user-images.githubusercontent.com/96176970/150545268-d159e296-0ebd-4155-ac3f-218dc31c7e9d.PNG)

**Expected result:**User should be able log in with Facebook.

**Comment by boris-giga** [comment]
actually, it works on Staging
now, it should work on https://horondi-front.azurewebsites.net/

**Comment by VeronikaChorna** [comment]
Thank you. I will correct it

пт, 21 янв. 2022 г. в 19:21, Boris Giga ***@***.***>:
