### ISSUE TITLE
[Create by yourself. Size] 'Size' dropdown contains duplicates.

### ISSUE THREAD

**Issue by mariia-matiiv** [ita-social-projects/horondi_client_be#1070]
Environment: Windows 10, Chrome Version 96.0.4664.110
Reproducible: Always

**Preconditions**
Go to https://horondi-front-staging.azurewebsites.net/

**Steps to reproduce:**
1. Click on Burger menu
2. Select "Create by yourself"
3. Click on 'Size' dropdown menu 

**Actual Result**
'M' option is duplicated

**Expected Result**
Size dropdown does not contain duplicates.

![image](https://user-images.githubusercontent.com/96194957/150561680-65a64824-20e7-4059-9f5a-858877b4ea36.png)

**Comment by AlexanderBil** [comment]
This bug is related to add validation for checking if size is already created #1073. 
https://github.com/ita-social-projects/horondi_client_be/issues/1073
I removed duplicate sizes from the admin panel and everything is gone
