### ISSUE TITLE
[Wishlist] add to wishlist function doesn't work

### ISSUE THREAD

**Issue by VeronikaChorna** [ita-social-projects/horondi_client_be#1088]
Environment Windows 10, Chrome Version 96.0.4664.110
Reproducible: Always

**Preconditions:**

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Log in as a user

**Step to reproduce:**

1.  Click on burger menu
2.  Click on any category
3. Click on any item
4. Click on 'Add to wishlist button
5. Check if an item was added to wishlist 

**Actual result:**  wishlist is empty

https://user-images.githubusercontent.com/96176970/151527178-27e6bc07-0f95-46fb-8975-7a69f24daf0b.mp4

**Expected result:** selected item is present in wishlist

**Comment by anemyro** [comment]
This bug couldn't have been reproduced yet.
