### ISSUE TITLE
(SP:5) Update items fix

### ISSUE THREAD

**Issue by MMashivskij** [ita-social-projects/horondi_client_be#517]

**Comment by moran711** [comment]
You need to write method that will help us to compare 2 states of item:
- object for update;
- object in database.
You don't need to compare full object, only fields that present in object for update.

For example:
object to update: 
```
{
   text: [],
   title: [],
}
```
object in database: 
```
{
   _id: '...',
  __v0: 0
   text: [],
   title: [],
   name: []
   images: []
}
```
Method or function need to compare `text` and `title `field in objects and return true if data in this field will be equal in 2 objects.
