### ISSUE TITLE
(SP:5)Create mockups for email templates

### ISSUE THREAD

**Issue by Kiyooooko** [ita-social-projects/horondi_client_be#545]
- [x] successful confirm
- [x] confirm email
- [x] block/unlock user
- [x] incomplete operations in cart
- [x] successful order

**Comment by grebiniuk** [comment]
Added: 
1. Account banned/unbanned
2. Mobile versions of the same emails
3. Also added an alternative, wider, header that can be used on all the templates.

Happy coding!
