### ISSUE TITLE
[Change Password field] won't load

### ISSUE THREAD

**Issue by VolodymyrVasylkiv** [ita-social-projects/horondi_client_be#991]
**Environment:**

OS Windows 10, Google Chrome Version 92.0.4515.131 ( 64 )

**Steps to reproduce**

1. Go to 'Horondi'
2. Log in (Google form)
3. Click on 'Profile menu'
3. Click on 'Change Password' field

**Actual result**
When clicking ‘Change password’ button, change password field won't load 
[As a user I want to see Profile page ita-social-projects/horondi_client_fe#150.docx](https://github.com/ita-social-projects/horondi_client_fe/files/6953333/As.a.user.I.want.to.see.Profile.page.150.docx)

Problem on backend with REGION field

**Expected result**
Change password field is working.

User story ita-social-projects/horondi_client_fe#150
https://github.com/ita-social-projects/horondi_client_fe/issues/150

**Comment by MariiaDakh** [comment]
After clicking on "Change password" button confirmation letter doesn't get sent to the indicated email adress
